version: '3.8'

services:
  asker:
    container_name: asker
    build:
      context: ..
      dockerfile: build/asker/Dockerfile
    env_file:
      - ../configs/asker.env
      - ../configs/secrets.env
    ports:
      - '80:8080'
    command: ['sh', '-c', './wait-for-it.sh postgres:5432 -t 30 && ./asker']
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:14.5-alpine
    restart: always
    env_file:
      - ../configs/secrets.env
    ports:
      - '5432:5432'
    volumes:
      - pg:/var/lib/postgresql/data
      - ../migrations/pg/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql:ro

volumes:
  pg:
    driver: local
